# Generated by Django 5.0 on 2024-01-05 17:07

from django.db import migrations, models
from django.core.validators import MaxValueValidator


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("lastname", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("sub1", models.IntegerField(default=0, validators=[MaxValueValidator(99)])),
                ("sub2", models.IntegerField(default=0, validators=[MaxValueValidator(99)])),
                ("sub3", models.IntegerField(default=0, validators=[MaxValueValidator(99)])),
                ("sub4", models.IntegerField(default=0, validators=[MaxValueValidator(99)])),
                ("sub5", models.IntegerField(default=0, validators=[MaxValueValidator(99)])),
             ],
        ),
    ]
