# Generated by Django 5.0 on 2024-01-08 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="sub2",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="sub3",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="sub4",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="sub5",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
    ]
