# Generated by Django 5.0 on 2024-01-08 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0002_alter_service_sub2_alter_service_sub3_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="sub1",
            field=models.IntegerField(
                validators=[django.core.validators.MaxValueValidator(99)]
            ),
        ),
    ]
